# Generated by Django 4.1.5 on 2023-04-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='photo',
        ),
    ]
