# Generated by Django 4.1.5 on 2023-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_employees_phone_remove_employees_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
