# Generated by Django 4.1.5 on 2023-04-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_employees_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
